In [1]:
import numpy as np
import pandas as pd

In [2]:
myData = pd.read_csv('Iris.csv')

In [3]:
myData

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [4]:
Sep = pd.Series(myData.SepalLengthCm)

In [5]:
Sep.mean()

5.843333333333335

In [6]:
Sep.median()

5.8

In [7]:
Sep.skew()

0.3149109566369728

In [8]:
Sep.kurt()

-0.5520640413156395

In [9]:
Sep.kurtosis()

-0.5520640413156395

In [10]:
cs=Sep.cumsum()

In [11]:
cs

0        5.1
1       10.0
2       14.7
3       19.3
4       24.3
       ...  
145    851.6
146    857.9
147    864.4
148    870.6
149    876.5
Name: SepalLengthCm, Length: 150, dtype: float64

In [12]:
myData.describe(include="all")

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
count   150.000000     150.000000    150.000000     150.000000    150.000000   
unique         NaN            NaN           NaN            NaN           NaN   
top            NaN            NaN           NaN            NaN           NaN   
freq           NaN            NaN           NaN            NaN           NaN   
mean     75.500000       5.843333      3.054000       3.758667      1.198667   
std      43.445368       0.828066      0.433594       1.764420      0.763161   
min       1.000000       4.300000      2.000000       1.000000      0.100000   
25%      38.250000       5.100000      2.800000       1.600000      0.300000   
50%      75.500000       5.800000      3.000000       4.350000      1.300000   
75%     112.750000       6.400000      3.300000       5.100000      1.800000   
max     150.000000       7.900000      4.400000       6.900000      2.500000   

            Species  
count           150  
unique            3  
top     Iris-setosa  
freq             50  
mean            NaN  
std             NaN  
min             NaN  
25%             NaN  
50%             NaN  
75%             NaN  
max             NaN

In [13]:
myData

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [14]:
myData.tail()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica

In [15]:
ser = pd.Series(np.random.rand(7))

In [16]:
ser

0    0.918066
1    0.727959
2    0.107517
3    0.940534
4    0.338879
5    0.145480
6    0.755588
dtype: float64

In [17]:
newdf = pd.DataFrame(np.random.rand(334,5), index = np.arange(334))

In [18]:
newdf

0         1         2         3         4
0    0.234046  0.321414  0.447885  0.800382  0.776157
1    0.605159  0.251722  0.876063  0.906049  0.227268
2    0.346432  0.260942  0.461695  0.724874  0.141755
3    0.319119  0.596981  0.382728  0.366957  0.934491
4    0.976809  0.706636  0.752684  0.986324  0.671085
..        ...       ...       ...       ...       ...
329  0.225005  0.495566  0.687279  0.082345  0.048840
330  0.794263  0.340483  0.981171  0.168398  0.166115
331  0.357801  0.753625  0.028218  0.395173  0.635905
332  0.486229  0.939932  0.372109  0.840467  0.310529
333  0.622005  0.042342  0.366383  0.649594  0.020173

[334 rows x 5 columns]

In [19]:

newdf.describe(include="all")

0           1           2           3           4
count  334.000000  334.000000  334.000000  334.000000  334.000000
mean     0.499357    0.495544    0.486950    0.494635    0.493961
std      0.305876    0.304158    0.286436    0.290858    0.278071
min      0.000364    0.005183    0.005199    0.003558    0.011208
25%      0.225027    0.211681    0.245485    0.241161    0.255799
50%      0.498814    0.488219    0.480445    0.492548    0.506443
75%      0.782205    0.773335    0.735652    0.744018    0.729685
max      0.999279    0.999985    0.999091    0.998340    0.995172

In [20]:
newdf.dtypes

0    float64
1    float64
2    float64
3    float64
4    float64
dtype: object

In [21]:
newdf.to_numpy()

array([[0.23404582, 0.32141352, 0.44788511, 0.80038206, 0.77615706],
       [0.60515898, 0.25172218, 0.87606268, 0.90604921, 0.22726762],
       [0.34643154, 0.26094229, 0.46169504, 0.72487417, 0.14175509],
       ...,
       [0.3578014 , 0.75362466, 0.02821815, 0.39517283, 0.63590459],
       [0.48622869, 0.93993239, 0.37210891, 0.84046663, 0.31052867],
       [0.62200473, 0.04234211, 0.36638339, 0.64959365, 0.02017327]])

In [22]:
newdf.T

0         1         2         3         4         5         6    \
0  0.234046  0.605159  0.346432  0.319119  0.976809  0.037711  0.082733   
1  0.321414  0.251722  0.260942  0.596981  0.706636  0.957506  0.952554   
2  0.447885  0.876063  0.461695  0.382728  0.752684  0.699327  0.785596   
3  0.800382  0.906049  0.724874  0.366957  0.986324  0.185515  0.613081   
4  0.776157  0.227268  0.141755  0.934491  0.671085  0.813400  0.808115   

        7         8         9    ...       324       325       326       327  \
0  0.632177  0.036980  0.131104  ...  0.569616  0.775285  0.212250  0.878077   
1  0.398498  0.458459  0.103045  ...  0.185368  0.936763  0.723108  0.281384   
2  0.912758  0.836237  0.389956  ...  0.139237  0.258478  0.653802  0.520615   
3  0.761424  0.103865  0.645334  ...  0.833519  0.467863  0.626898  0.491240   
4  0.458077  0.016620  0.061835  ...  0.654447  0.358657  0.377197  0.596898   

        328       329       330       331       332       333  
0  0.618755  0.225005  0.794263  0.357801  0.486229  0.622005  
1  0.969336  0.495566  0.340483  0.753625  0.939932  0.042342  
2  0.804238  0.687279  0.981171  0.028218  0.372109  0.366383  
3  0.771303  0.082345  0.168398  0.395173  0.840467  0.649594  
4  0.296786  0.048840  0.166115  0.635905  0.310529  0.020173  

[5 rows x 334 columns]

In [23]:
newdf


0         1         2         3         4
0    0.234046  0.321414  0.447885  0.800382  0.776157
1    0.605159  0.251722  0.876063  0.906049  0.227268
2    0.346432  0.260942  0.461695  0.724874  0.141755
3    0.319119  0.596981  0.382728  0.366957  0.934491
4    0.976809  0.706636  0.752684  0.986324  0.671085
..        ...       ...       ...       ...       ...
329  0.225005  0.495566  0.687279  0.082345  0.048840
330  0.794263  0.340483  0.981171  0.168398  0.166115
331  0.357801  0.753625  0.028218  0.395173  0.635905
332  0.486229  0.939932  0.372109  0.840467  0.310529
333  0.622005  0.042342  0.366383  0.649594  0.020173

[334 rows x 5 columns]

In [24]:
newdf[1]

0      0.321414
1      0.251722
2      0.260942
3      0.596981
4      0.706636
         ...   
329    0.495566
330    0.340483
331    0.753625
332    0.939932
333    0.042342
Name: 1, Length: 334, dtype: float64

In [25]:
newdf2=newdf.copy()


In [26]:
newdf2


0         1         2         3         4
0    0.234046  0.321414  0.447885  0.800382  0.776157
1    0.605159  0.251722  0.876063  0.906049  0.227268
2    0.346432  0.260942  0.461695  0.724874  0.141755
3    0.319119  0.596981  0.382728  0.366957  0.934491
4    0.976809  0.706636  0.752684  0.986324  0.671085
..        ...       ...       ...       ...       ...
329  0.225005  0.495566  0.687279  0.082345  0.048840
330  0.794263  0.340483  0.981171  0.168398  0.166115
331  0.357801  0.753625  0.028218  0.395173  0.635905
332  0.486229  0.939932  0.372109  0.840467  0.310529
333  0.622005  0.042342  0.366383  0.649594  0.020173

[334 rows x 5 columns]

In [27]:
newdf[0][0]=0.34

In [28]:
newdf2

0         1         2         3         4
0    0.234046  0.321414  0.447885  0.800382  0.776157
1    0.605159  0.251722  0.876063  0.906049  0.227268
2    0.346432  0.260942  0.461695  0.724874  0.141755
3    0.319119  0.596981  0.382728  0.366957  0.934491
4    0.976809  0.706636  0.752684  0.986324  0.671085
..        ...       ...       ...       ...       ...
329  0.225005  0.495566  0.687279  0.082345  0.048840
330  0.794263  0.340483  0.981171  0.168398  0.166115
331  0.357801  0.753625  0.028218  0.395173  0.635905
332  0.486229  0.939932  0.372109  0.840467  0.310529
333  0.622005  0.042342  0.366383  0.649594  0.020173

[334 rows x 5 columns]

In [29]:
newdf

0         1         2         3         4
0    0.340000  0.321414  0.447885  0.800382  0.776157
1    0.605159  0.251722  0.876063  0.906049  0.227268
2    0.346432  0.260942  0.461695  0.724874  0.141755
3    0.319119  0.596981  0.382728  0.366957  0.934491
4    0.976809  0.706636  0.752684  0.986324  0.671085
..        ...       ...       ...       ...       ...
329  0.225005  0.495566  0.687279  0.082345  0.048840
330  0.794263  0.340483  0.981171  0.168398  0.166115
331  0.357801  0.753625  0.028218  0.395173  0.635905
332  0.486229  0.939932  0.372109  0.840467  0.310529
333  0.622005  0.042342  0.366383  0.649594  0.020173

[334 rows x 5 columns]

In [30]:
newdf.columns=list("ABCDE")

In [31]:
newdf

A         B         C         D         E
0    0.340000  0.321414  0.447885  0.800382  0.776157
1    0.605159  0.251722  0.876063  0.906049  0.227268
2    0.346432  0.260942  0.461695  0.724874  0.141755
3    0.319119  0.596981  0.382728  0.366957  0.934491
4    0.976809  0.706636  0.752684  0.986324  0.671085
..        ...       ...       ...       ...       ...
329  0.225005  0.495566  0.687279  0.082345  0.048840
330  0.794263  0.340483  0.981171  0.168398  0.166115
331  0.357801  0.753625  0.028218  0.395173  0.635905
332  0.486229  0.939932  0.372109  0.840467  0.310529
333  0.622005  0.042342  0.366383  0.649594  0.020173

[334 rows x 5 columns]

In [32]:
 newdf.loc[[1,2],['B']]

B
1  0.251722
2  0.260942

In [33]:
newdf

A         B         C         D         E
0    0.340000  0.321414  0.447885  0.800382  0.776157
1    0.605159  0.251722  0.876063  0.906049  0.227268
2    0.346432  0.260942  0.461695  0.724874  0.141755
3    0.319119  0.596981  0.382728  0.366957  0.934491
4    0.976809  0.706636  0.752684  0.986324  0.671085
..        ...       ...       ...       ...       ...
329  0.225005  0.495566  0.687279  0.082345  0.048840
330  0.794263  0.340483  0.981171  0.168398  0.166115
331  0.357801  0.753625  0.028218  0.395173  0.635905
332  0.486229  0.939932  0.372109  0.840467  0.310529
333  0.622005  0.042342  0.366383  0.649594  0.020173

[334 rows x 5 columns]

In [34]:
newdf.head(3)


A         B         C         D         E
0  0.340000  0.321414  0.447885  0.800382  0.776157
1  0.605159  0.251722  0.876063  0.906049  0.227268
2  0.346432  0.260942  0.461695  0.724874  0.141755

In [35]:
newdf.iloc[[1,2],[3,4]]

D         E
1  0.906049  0.227268
2  0.724874  0.141755

In [36]:
newdf


A         B         C         D         E
0    0.340000  0.321414  0.447885  0.800382  0.776157
1    0.605159  0.251722  0.876063  0.906049  0.227268
2    0.346432  0.260942  0.461695  0.724874  0.141755
3    0.319119  0.596981  0.382728  0.366957  0.934491
4    0.976809  0.706636  0.752684  0.986324  0.671085
..        ...       ...       ...       ...       ...
329  0.225005  0.495566  0.687279  0.082345  0.048840
330  0.794263  0.340483  0.981171  0.168398  0.166115
331  0.357801  0.753625  0.028218  0.395173  0.635905
332  0.486229  0.939932  0.372109  0.840467  0.310529
333  0.622005  0.042342  0.366383  0.649594  0.020173

[334 rows x 5 columns]

In [37]:
newdf.reset_index(drop=True,inplace=True)

In [38]:
newdf


A         B         C         D         E
0    0.340000  0.321414  0.447885  0.800382  0.776157
1    0.605159  0.251722  0.876063  0.906049  0.227268
2    0.346432  0.260942  0.461695  0.724874  0.141755
3    0.319119  0.596981  0.382728  0.366957  0.934491
4    0.976809  0.706636  0.752684  0.986324  0.671085
..        ...       ...       ...       ...       ...
329  0.225005  0.495566  0.687279  0.082345  0.048840
330  0.794263  0.340483  0.981171  0.168398  0.166115
331  0.357801  0.753625  0.028218  0.395173  0.635905
332  0.486229  0.939932  0.372109  0.840467  0.310529
333  0.622005  0.042342  0.366383  0.649594  0.020173

[334 rows x 5 columns]

In [39]:
myData.drop_duplicates(subset='SepalWidthCm')

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0    1            5.1           3.5            1.4           0.2   
1    2            4.9           3.0            1.4           0.2   
2    3            4.7           3.2            1.3           0.2   
3    4            4.6           3.1            1.5           0.2   
4    5            5.0           3.6            1.4           0.2   
5    6            5.4           3.9            1.7           0.4   
6    7            4.6           3.4            1.4           0.3   
8    9            4.4           2.9            1.4           0.2   
10  11            5.4           3.7            1.5           0.2   
14  15            5.8           4.0            1.2           0.2   
15  16            5.7           4.4            1.5           0.4   
18  19            5.7           3.8            1.7           0.3   
23  24            5.1           3.3            1.7           0.5   
32  33            5.2           4.1            1.5           0.1   
33  34            5.5           4.2            1.4           0.2   
41  42            4.5           2.3            1.3           0.3   
54  55            6.5           2.8            4.6           1.5   
57  58            4.9           2.4            3.3           1.0   
59  60            5.2           2.7            3.9           1.4   
60  61            5.0           2.0            3.5           1.0   
62  63            6.0           2.2            4.0           1.0   
69  70            5.6           2.5            3.9           1.1   
79  80            5.7           2.6            3.5           1.0   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
5       Iris-setosa  
6       Iris-setosa  
8       Iris-setosa  
10      Iris-setosa  
14      Iris-setosa  
15      Iris-setosa  
18      Iris-setosa  
23      Iris-setosa  
32      Iris-setosa  
33      Iris-setosa  
41      Iris-setosa  
54  Iris-versicolor  
57  Iris-versicolor  
59  Iris-versicolor  
60  Iris-versicolor  
62  Iris-versicolor  
69  Iris-versicolor  
79  Iris-versicolor

In [40]:
df = pd.DataFrame({
    'brand': ['Yum Yum', 'Yum Yum', 'Indomie', 'Indomie', 'Indomie'],
    'style': ['cup', 'cup', 'cup', 'pack', 'pack'],
    'rating': [4, 4, 3.5, 15, 5]
})

In [41]:
df

brand style  rating
0  Yum Yum   cup     4.0
1  Yum Yum   cup     4.0
2  Indomie   cup     3.5
3  Indomie  pack    15.0
4  Indomie  pack     5.0

In [42]:
df.drop_duplicates(subset=['brand'],keep='last')

brand style  rating
1  Yum Yum   cup     4.0
4  Indomie  pack     5.0

In [43]:
df['brand'].value_counts()

Indomie    3
Yum Yum    2
Name: brand, dtype: int64

In [44]:
Sheet=pd.read_excel('sheet.xlsx')

# numpy
* provides effcient storage
* fast
* ez to learn
* uses relatively less memory to store data


In [52]:
myArr = np.array([3,6,7,1,5],np.int64)

In [46]:
myArr

array([3, 6, 7, 1, 5])

In [47]:
myArr[2]

7

In [55]:
myArr.shape

(5,)

In [56]:
myArr.dtype

dtype('int64')

In [57]:
myArr[1]=77

In [58]:
myArr

array([ 3, 77,  7,  1,  5], dtype=int64)

**creating array: conversion from other python structures**

In [62]:
listArray = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [63]:
listArray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [64]:
listArray.shape

(3, 3)

In [66]:
listArray.size

9

In [65]:
np.array({11,22,33}, dtype=object)

array({33, 11, 22}, dtype=object)

**creating array: Intrinsic NumPy array creation functions**

In [67]:
zeros = np.zeros((2,5))

In [68]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [69]:
zeros.dtype

dtype('float64')

In [70]:
zeros.size

10

In [71]:
rng = np.arange(15)

In [72]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [73]:
rng.shape

(15,)

In [75]:
  lspace= np.linspace(1,10,5)

In [76]:
lspace

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [78]:
emp = np.empty((3,3))

emp

In [79]:
emplike = np.empty_like(lspace)

In [80]:
emplike

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [81]:
ide = np.identity(4)

In [82]:
ide

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [83]:
ide.shape

(4, 4)

In [84]:
ide.size

16

In [85]:
 rspArray = np.arange(15)

In [86]:
rspArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [88]:
rsp = rspArray.reshape(3,5)

In [89]:
rsp

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [92]:
rsp.shape

(3, 5)

In [90]:
rvl = rsp.ravel()

In [91]:
rvl

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [93]:
rvl.shape

(15,)

In [94]:
arrey = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [95]:
arrey.shape

(3, 3)

In [98]:
sum1=arrey.sum(axis=0)

In [99]:
sum1

array([12, 15, 18])

In [100]:
sum2 = arrey.sum(axis=1)

In [101]:
sum2

array([ 6, 15, 24])

In [102]:
arrey.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])